[package]
name = "lis2dh12"
version = "0.0.1"
authors = ["Tomas Kukosa <tkeksa@gmail.com>"]
repository = "https://github.com/tkeksa/lis2dh12"
license = "Apache-2.0 OR MIT"
description = "Platform-agnostic Rust driver for the LIS2DH12 accelerometer."
readme = "README.md"
keywords = ["accelerometer", "sensor", "i2c", "driver", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
edition = "2018"

[features]
default = []
out_f32 = []

[dependencies]
accelerometer = "0.6"
embedded-hal = "0.2"

[dependencies.cast]
default-features = false
version = "0.2"

[dev-dependencies]
embedded-hal-mock = "0.7"

[profile.release]
lto = true
